site_name: termin-modules
site_description: Система загрузки модулей для проектов termin
theme:
  name: material

nav:
  - Главная: index.md
  - Дескрипторы: descriptors.md
  - Жизненный цикл: lifecycle.md
  - Коллбеки: callbacks.md
  - Python API: python-api.md
